# .github/actions/check-permissions/action.yml
name: "Check Branch Permissions"
description: "Collect branch protection and merge settings and post a Markdown checklist on the Pull Request."
author: "Ricardo Malnati"
branding:
  icon: "shield"
  color: "blue"

inputs:
  token:
    description: "GitHub token (ex.: secrets.GITHUB_TOKEN)"
    required: true
  base_branch:
    description: "Nome do branch base a ser verificado (ex.: main, staging)"
    required: true
  pr_number:
    description: "Número da Pull Request a ser comentada"
    required: true

outputs:
  message_checklist:
    description: "Checklist em Markdown com configurações de merge e proteção do branch base."
    value: ${{ steps.build-checklist.outputs.message_checklist }}

runs:
  using: "composite"
  steps:
    - id: fetch-repo
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        set -euo pipefail
        GITHUB_API_URL="https://api.github.com"
        RESPONSE="$(curl -sS \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY")"
        {
          printf 'repo_json<<EOF\n%s\nEOF\n' "$RESPONSE"
        } >>"$GITHUB_OUTPUT"

    - id: fetch-protection
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        BASE_BRANCH: ${{ inputs.base_branch }}
      run: |
        set -euo pipefail
        GITHUB_API_URL="https://api.github.com"
        TMP_PROTECTION="$(mktemp)"
        STATUS="$(curl -sS \
          -o "$TMP_PROTECTION" \
          -w '%{http_code}' \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/branches/$BASE_BRANCH/protection")"
        BODY="$(cat "$TMP_PROTECTION" || echo '')"
        rm -f "$TMP_PROTECTION" || true
        {
          printf 'protection_json<<EOF\n%s\nEOF\n' "$BODY"
          echo "branch_prot_status=$STATUS"
        } >>"$GITHUB_OUTPUT"

    - id: compute-merge-settings
      shell: bash
      env:
        REPO_JSON: ${{ steps.fetch-repo.outputs.repo_json }}
      run: |
        set -euo pipefail

        emoji() {
          case "$1" in
            true) printf '✅' ;;
            false) printf '❌' ;;
            null|'') printf '❔' ;;
            *) printf '❌' ;;
          esac
        }

        ALLOW_REBASE="$(printf '%s' "$REPO_JSON" | jq -r '.allow_rebase_merge')"
        ALLOW_SQUASH="$(printf '%s' "$REPO_JSON" | jq -r '.allow_squash_merge')"
        ALLOW_MERGE_COMMIT="$(printf '%s' "$REPO_JSON" | jq -r '.allow_merge_commit')"
        ALLOW_AUTO_MERGE="$(printf '%s' "$REPO_JSON" | jq -r '.allow_auto_merge')"
        DELETE_BRANCH_ON_MERGE="$(printf '%s' "$REPO_JSON" | jq -r '.delete_branch_on_merge')"
        DEFAULT_BRANCH="$(printf '%s' "$REPO_JSON" | jq -r '.default_branch // ""')"

        ALLOW_REBASE_EMOJI="$(emoji "$ALLOW_REBASE")"
        ALLOW_SQUASH_EMOJI="$(emoji "$ALLOW_SQUASH")"
        ALLOW_MERGE_COMMIT_EMOJI="$(emoji "$ALLOW_MERGE_COMMIT")"
        ALLOW_AUTO_MERGE_EMOJI="$(emoji "$ALLOW_AUTO_MERGE")"
        DELETE_BRANCH_ON_MERGE_EMOJI="$(emoji "$DELETE_BRANCH_ON_MERGE")"

        {
          echo "allow_rebase_emoji=$ALLOW_REBASE_EMOJI"
          echo "allow_squash_emoji=$ALLOW_SQUASH_EMOJI"
          echo "allow_merge_commit_emoji=$ALLOW_MERGE_COMMIT_EMOJI"
          echo "allow_auto_merge_emoji=$ALLOW_AUTO_MERGE_EMOJI"
          echo "delete_branch_on_merge_emoji=$DELETE_BRANCH_ON_MERGE_EMOJI"
          echo "default_branch=$DEFAULT_BRANCH"
        } >>"$GITHUB_OUTPUT"

    - id: compute-protection-section
      shell: bash
      env:
        PROTECTION_JSON: ${{ steps.fetch-protection.outputs.protection_json }}
        BRANCH_PROT_STATUS: ${{ steps.fetch-protection.outputs.branch_prot_status }}
        BASE_BRANCH: ${{ inputs.base_branch }}
      run: |
        set -euo pipefail

        emoji() {
          case "$1" in
            true) printf '✅' ;;
            false) printf '❌' ;;
            null|'') printf '❔' ;;
            *) printf '❌' ;;
          esac
        }

        PROTECTION_NOTE=""
        LINEAR_HISTORY_EMOJI="❔"
        REQUIRED_STATUS_EMOJI="❔"
        STRICT_LINE=""
        REQUIRED_APPROVING="0"
        ENFORCE_ADMINS_EMOJI="❔"
        RESTRICTIONS_EMOJI="❔"

        if [ "$BRANCH_PROT_STATUS" = "200" ]; then
          LINEAR_HISTORY="$(printf '%s' "$PROTECTION_JSON" | jq -r '.required_linear_history.enabled // .required_linear_history // empty')"
          REQUIRED_STATUS_CHECKS_PRESENT="$(printf '%s' "$PROTECTION_JSON" | jq -r 'if .required_status_checks and ((.required_status_checks.checks // []) + (.required_status_checks.contexts // []) | length) > 0 then "true" else "false" end')"
          STRICT_STATUS="$(printf '%s' "$PROTECTION_JSON" | jq -r '.required_status_checks.strict // empty')"
          REQUIRED_APPROVING="$(printf '%s' "$PROTECTION_JSON" | jq -r '.required_pull_request_reviews.required_approving_review_count // empty')"
          ENFORCE_ADMINS="$(printf '%s' "$PROTECTION_JSON" | jq -r '.enforce_admins.enabled // .enforce_admins // empty')"
          RESTRICTIONS_PRESENT="$(printf '%s' "$PROTECTION_JSON" | jq -r 'if .restrictions and (((.restrictions.users // []) + (.restrictions.teams // []) + (.restrictions.apps // []) | length) > 0) then "true" else "false" end')"

          LINEAR_HISTORY_EMOJI="$(emoji "$LINEAR_HISTORY")"
          REQUIRED_STATUS_EMOJI="$(emoji "$REQUIRED_STATUS_CHECKS_PRESENT")"
          STRICT_STATUS_EMOJI="$(emoji "$STRICT_STATUS")"
          ENFORCE_ADMINS_EMOJI="$(emoji "$ENFORCE_ADMINS")"
          RESTRICTIONS_EMOJI="$(emoji "$RESTRICTIONS_PRESENT")"

          if [ -z "$REQUIRED_APPROVING" ] || [ "$REQUIRED_APPROVING" = "null" ]; then
            REQUIRED_APPROVING="0"
          fi

          if [ "$REQUIRED_STATUS_CHECKS_PRESENT" = "true" ] || [ "$STRICT_STATUS" = "true" ] || [ "$STRICT_STATUS" = "false" ]; then
            STRICT_LINE="- Exigir branch atualizado para merge: $STRICT_STATUS_EMOJI"
          fi
        else
          PROTECTION_NOTE="⚠️ Não foi possível ler a proteção do branch \`$BASE_BRANCH\` (status HTTP $BRANCH_PROT_STATUS)."
          STRICT_LINE="- Não foi possível ler configurações detalhadas (HTTP $BRANCH_PROT_STATUS)"
        fi

        {
          echo "protection_note=$PROTECTION_NOTE"
          echo "linear_history_emoji=$LINEAR_HISTORY_EMOJI"
          echo "required_status_emoji=$REQUIRED_STATUS_EMOJI"
          echo "strict_line=$STRICT_LINE"
          echo "required_approving=$REQUIRED_APPROVING"
          echo "enforce_admins_emoji=$ENFORCE_ADMINS_EMOJI"
          echo "restrictions_emoji=$RESTRICTIONS_EMOJI"
        } >>"$GITHUB_OUTPUT"

    - id: build-checklist
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
        BASE_BRANCH: ${{ inputs.base_branch }}
        ALLOW_REBASE_EMOJI: ${{ steps.compute-merge-settings.outputs.allow_rebase_emoji }}
        ALLOW_SQUASH_EMOJI: ${{ steps.compute-merge-settings.outputs.allow_squash_emoji }}
        ALLOW_MERGE_COMMIT_EMOJI: ${{ steps.compute-merge-settings.outputs.allow_merge_commit_emoji }}
        ALLOW_AUTO_MERGE_EMOJI: ${{ steps.compute-merge-settings.outputs.allow_auto_merge_emoji }}
        DELETE_BRANCH_ON_MERGE_EMOJI: ${{ steps.compute-merge-settings.outputs.delete_branch_on_merge_emoji }}
        DEFAULT_BRANCH: ${{ steps.compute-merge-settings.outputs.default_branch }}
        PROTECTION_NOTE: ${{ steps.compute-protection-section.outputs.protection_note }}
        LINEAR_HISTORY_EMOJI: ${{ steps.compute-protection-section.outputs.linear_history_emoji }}
        REQUIRED_STATUS_EMOJI: ${{ steps.compute-protection-section.outputs.required_status_emoji }}
        STRICT_LINE: ${{ steps.compute-protection-section.outputs.strict_line }}
        REQUIRED_APPROVING: ${{ steps.compute-protection-section.outputs.required_approving }}
        ENFORCE_ADMINS_EMOJI: ${{ steps.compute-protection-section.outputs.enforce_admins_emoji }}
        RESTRICTIONS_EMOJI: ${{ steps.compute-protection-section.outputs.restrictions_emoji }}
      run: |
        set -euo pipefail
        CHECKLIST_MSG="$(envsubst < "$GITHUB_ACTION_PATH/template.md")"
        {
          printf 'message_checklist<<EOF\n%s\nEOF\n' "$CHECKLIST_MSG"
        } >>"$GITHUB_OUTPUT"

    - id: comment-checklist
      uses: Malnati/pr-comment@v4
      with:
        token: ${{ inputs.token }}
        pr_number: ${{ inputs.pr_number }}
        header_actor: ${{ github.actor }}
        header_title: "📋 Checklist de proteção de branch"
        header_subject: "Regras aplicadas ao branch base ${{ inputs.base_branch }}"
        body_message: ${{ steps.build-checklist.outputs.message_checklist }}
        body_scope: ""
        body_todo: ""
        footer_result: "Checklist gerada automaticamente."
        footer_advise: "Revise as regras antes de ajustar a estratégia de merge."
